site_name: wavepeek
site_url: https://kleverhq.github.io/wavepeek/
repo_url: https://github.com/kleverhq/wavepeek
repo_name: kleverhq/wavepeek
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
plugins:
  - search
markdown_extensions:
  - admonition
  - toc:
      permalink: true
extra:
  version:
    provider: mike
